// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsdbTiFIYYjUkCaTlSlVsKgOgOaBPHvJI',
    appId: '1:586494298969:web:d9b80311009788ecf3da48',
    messagingSenderId: '586494298969',
    projectId: 'sekolah-beta-ecommerce',
    authDomain: 'sekolah-beta-ecommerce.firebaseapp.com',
    storageBucket: 'sekolah-beta-ecommerce.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCT_yo7_YxmuLVWEdSDkpckYJ4DpwJ7ySY',
    appId: '1:586494298969:android:04e30e49d509d9d9f3da48',
    messagingSenderId: '586494298969',
    projectId: 'sekolah-beta-ecommerce',
    storageBucket: 'sekolah-beta-ecommerce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdaWQlUwvHcOmCYio26fjN45rHzjbfqt8',
    appId: '1:586494298969:ios:f032d0d67f6e55adf3da48',
    messagingSenderId: '586494298969',
    projectId: 'sekolah-beta-ecommerce',
    storageBucket: 'sekolah-beta-ecommerce.appspot.com',
    iosClientId: '586494298969-vhaglm2ib0kst7iaj4lshvenkv9ijddn.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerce',
  );
}
